Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.hostname = "manager"
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.provider 'virtualbox' do |v| 
    v.memory=2048
  end
end
