Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.hostname = "jenkins"
  config.vm.network 'forwarded_port', guest: 8080, host:8080
  config.vm.network "private_network", ip: "192.168.56.7"
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.provider 'virtualbox' do |v| 
    v.memory=1024
  end

end
